apiVersion: v1
kind: Service

metadata:
  name: vehicle-sales-service

spec:
  type: NodePort

  selector:
    app: vehicle-sales-service

  ports:
    - port: ${PORT}
      targetPort: ${PORT}
      nodePort: ${NODE_PORT}